### ISSUE TITLE
I want to set a default value for message_sensor. I don't know how to write config.schema.yaml files.

### ISSUE THREAD

**Issue by chain312** [StackStorm-Exchange/stackstorm-kafka#17]
I configured it this way but it didn't work.
```
    message_sensor:
    description: "Sensor specific settings"
    type: "object"
    required: true
    additionalProperties: true
    properties:
      hosts:
        description: "List of Kafka brokers hosts:port for sensor to connect to"
        type: "string"
        default: "kafka-headless:9092"
        required: true
      topics:
        description: "List of topics for the sensor to subscribe to"
        type: "array"
        items:
          type: "string"
          default:
            - test1
            - test2
            - test3
            - test4
          required: true
      group_id:
        description: "The sensors group ID"
        type: "string"
        default: "soargcpgroup"
        required: true
      client_id:
        description: "The sensors client ID"
        type: "string"
        default: "soargcpclient"
        required: true
```
![image](https://user-images.githubusercontent.com/30886624/234226833-688732d3-449c-4878-8559-0db6e61f627b.png)
I want message_sensor to be this value {"client_id": "soargcpclient", "group_id": "soargcpgroup", "hosts": "kafka-headless:9092", "topics": ["test1", "test2", "test3", "test4"]}, but this value is '{}'
